spring.application.name=ticket-management

# L?y thông tin t? Bi?n môi tr??ng (Environment Variables) - Không commit m?t kh?u
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/ticket_management}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# B?T BU?C THEO M?C 3.2: ddl-auto=validate (DB qu?n lý b?ng file SQL th? công)
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
